// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RumoRestaurantes.Context;

#nullable disable

namespace RumoRestaurantes.Migrations
{
    [DbContext(typeof(PedidoContext))]
    partial class PedidoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RumoRestaurantes.Models.PedidoCliente", b =>
                {
                    b.Property<int>("PedidoClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PedidoClienteId"));

                    b.Property<string>("Bebida")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataHoraPedido")
                        .HasColumnType("datetime2");

                    b.Property<int>("Mesa")
                        .HasColumnType("int");

                    b.Property<string>("NomeSolicitante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("PedidoClienteId");

                    b.ToTable("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
